type Query {
  recipe(id: ID): Recipe
  pid: Int
}
type Recipe {
  id: ID!
  name: String!
  steps: String
  ingredients: [Ingredient]!
}
type Ingredient {
  id: ID!
  name: String!
  quantity: String
}
